
tasks:
  - init: npm install
    command: npm run start



vscode:
  extensions:
    - esbenp.prettier-vscode
    - mintlify.document
    - dsznajder.es7-react-js-snippets
    - bradlc.vscode-tailwindcss
